### ISSUE TITLE
Possible to port Corne Keyboard?

### ISSUE THREAD

**Issue by mejobloggs** [Huckies/qmk_port_ch582#147]
Hello, I would love to use Corne Keyboard with ch582, is it possible?

https://github.com/qmk/qmk_firmware/blob/master/keyboards/crkbd/keymaps/default/keymap.c

https://github.com/qmk/qmk_firmware/blob/master/keyboards/crkbd/readme.md

Thank you for making qmk_port_ch582, very cool

**Comment by Huckies** [comment]
Hello, mejobloggs.

Unfortunately there is no split support at this time, and this situation may last quite a long time until I found a decent way to implement true-wireless-keyboard just like the last generation of TWS earphones do.

**Comment by mejobloggs** [comment]
What about wired connection? Many DIY split keyboards are wired together with TRSS.

I saw a few mentions of this qmk ch582 port on reddit and I think people would be very interested in wired split.

WeAct CH582 on AliExpress looks a really good competitor to Pro Micro and other boards people use.

Anyway feel free to close this if you want 👍

**Comment by Huckies** [comment]
Wired connection do make things much simpler but it's a side quest rather than a milestone: hardly any jobs can be reused on true-wireless-connections.So any PR on this is welcomed, please notice that the format requirements on basic codes are much higher than porting a keyboard.  
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        11/4/2023 11:39
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Wyatt ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [O-H-M2/qmk_port_ch582] Possible to port Corne Keyboard? (Issue #147)
        
      
    
  

What about wired connection? Many DIY split keyboards are wired together with TRSS.
I saw a few mentions of this qmk ch582 port on reddit and I think people would be very interested in wired split.
WeAct CH582 on AliExpress looks a really good competitor to Pro Micro and other boards people use.
Anyway feel free to close this if you want 👍
